"""all tables

Revision ID: 03a285f0cff4
Revises: 
Create Date: 2020-02-15 10:57:03.034634

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '03a285f0cff4'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('hashed_password', sa.Binary(), nullable=False),
    sa.Column('authenticated', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('maxes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('squat', sa.Float(), nullable=True),
    sa.Column('bench', sa.Float(), nullable=True),
    sa.Column('deadlift', sa.Float(), nullable=True),
    sa.Column('press', sa.Float(), nullable=True),
    sa.Column('date_time', sa.DateTime(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('posts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=80), nullable=True),
    sa.Column('warm_up', sa.String(length=80), nullable=True),
    sa.Column('accessories', sa.String(length=80), nullable=True),
    sa.Column('conditioning', sa.String(length=80), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('posts')
    op.drop_table('maxes')
    op.drop_table('users')
    # ### end Alembic commands ###
