"""main lift back to string, sets added

Revision ID: 07e50c48c3ed
Revises: fe0034418c11
Create Date: 2020-02-29 22:04:12.152918

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '07e50c48c3ed'
down_revision = 'fe0034418c11'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('sets', sa.PickleType(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'sets')
    # ### end Alembic commands ###
