"""pickle type for posts

Revision ID: 482dafbb68eb
Revises: 2ec2c5f24938
Create Date: 2020-02-15 20:24:22.060323

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '482dafbb68eb'
down_revision = '2ec2c5f24938'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('main_lift', sa.PickleType(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'main_lift')
    # ### end Alembic commands ###
