"""empty message

Revision ID: 6469ed3a8b9e
Revises: 4eeafb8e3732
Create Date: 2020-08-09 14:59:52.294086

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '6469ed3a8b9e'
down_revision = '4eeafb8e3732'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('general_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('unit', sa.String(length=20), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('accessory_lifts', sa.Column('user_id', sa.Integer(), nullable=True))
    op.alter_column('accessory_lifts', 'lift',
               existing_type=mysql.VARCHAR(length=60),
               nullable=False)
    op.create_foreign_key(None, 'accessory_lifts', 'users', ['user_id'], ['id'])
    op.drop_index('ix_users_email', table_name='users')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_users_email', 'users', ['email'], unique=False)
    op.drop_constraint(None, 'accessory_lifts', type_='foreignkey')
    op.alter_column('accessory_lifts', 'lift',
               existing_type=mysql.VARCHAR(length=60),
               nullable=True)
    op.drop_column('accessory_lifts', 'user_id')
    op.drop_table('general_settings')
    # ### end Alembic commands ###
