"""Accessories  to PickleType Add Tables Back

Revision ID: 6ffcd15e8d40
Revises: ffe4658a4846
Create Date: 2020-03-31 15:24:26.481695

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6ffcd15e8d40'
down_revision = 'ffe4658a4846'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('accessory_lifts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lift', sa.String(length=60), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('posts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=80), nullable=True),
    sa.Column('warm_up', sa.String(length=80), nullable=True),
    sa.Column('main_lift', sa.String(length=20), nullable=True),
    sa.Column('sets', sa.PickleType(), nullable=True),
    sa.Column('accessories', sa.PickleType(), nullable=True),
    sa.Column('conditioning', sa.String(length=80), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_posts_timestamp'), 'posts', ['timestamp'], unique=False)
    op.create_index(op.f('ix_posts_title'), 'posts', ['title'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_posts_title'), table_name='posts')
    op.drop_index(op.f('ix_posts_timestamp'), table_name='posts')
    op.drop_table('posts')
    op.drop_table('accessory_lifts')
    # ### end Alembic commands ###
