"""one to one relationship

Revision ID: 083042a08455
Revises: 0eafbb1a68e4
Create Date: 2020-03-18 18:54:38.851521

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '083042a08455'
down_revision = '0eafbb1a68e4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('squat_personal_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('one_rep', sa.Float(), nullable=True),
    sa.Column('two_reps', sa.Float(), nullable=True),
    sa.Column('three_reps', sa.Float(), nullable=True),
    sa.Column('four_reps', sa.Float(), nullable=True),
    sa.Column('five_reps', sa.Float(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_squat_personal_records_timestamp'), 'squat_personal_records', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_squat_personal_records_timestamp'), table_name='squat_personal_records')
    op.drop_table('squat_personal_records')
    # ### end Alembic commands ###
