"""email unique, index off

Revision ID: 0eafbb1a68e4
Revises: ddedbfd2765a
Create Date: 2020-03-14 11:42:50.860900

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0eafbb1a68e4'
down_revision = 'ddedbfd2765a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'users', ['email'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    # ### end Alembic commands ###
