"""empty message

Revision ID: 1ebb34155a95
Revises: 6469ed3a8b9e
Create Date: 2020-08-09 16:44:24.130427

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1ebb34155a95'
down_revision = '6469ed3a8b9e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('hashed_password', sa.String(length=128), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('authenticated', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_table('accessory_lifts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lift', sa.String(length=60), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('bench_personal_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('one_rep', sa.Float(), nullable=True),
    sa.Column('two_reps', sa.Float(), nullable=True),
    sa.Column('three_reps', sa.Float(), nullable=True),
    sa.Column('four_reps', sa.Float(), nullable=True),
    sa.Column('five_reps', sa.Float(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bench_personal_records_timestamp'), 'bench_personal_records', ['timestamp'], unique=False)
    op.create_table('deadlift_personal_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('one_rep', sa.Float(), nullable=True),
    sa.Column('two_reps', sa.Float(), nullable=True),
    sa.Column('three_reps', sa.Float(), nullable=True),
    sa.Column('four_reps', sa.Float(), nullable=True),
    sa.Column('five_reps', sa.Float(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_deadlift_personal_records_timestamp'), 'deadlift_personal_records', ['timestamp'], unique=False)
    op.create_table('general_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('unit', sa.String(length=20), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('maxes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('squat', sa.Float(), nullable=True),
    sa.Column('bench', sa.Float(), nullable=True),
    sa.Column('deadlift', sa.Float(), nullable=True),
    sa.Column('press', sa.Float(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_maxes_timestamp'), 'maxes', ['timestamp'], unique=False)
    op.create_table('posts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=80), nullable=True),
    sa.Column('warm_up', sa.String(length=80), nullable=True),
    sa.Column('main_lift', sa.String(length=20), nullable=True),
    sa.Column('sets', sa.PickleType(), nullable=True),
    sa.Column('accessories', sa.PickleType(), nullable=True),
    sa.Column('conditioning', sa.String(length=80), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_posts_timestamp'), 'posts', ['timestamp'], unique=False)
    op.create_index(op.f('ix_posts_title'), 'posts', ['title'], unique=False)
    op.create_table('press_personal_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('one_rep', sa.Float(), nullable=True),
    sa.Column('two_reps', sa.Float(), nullable=True),
    sa.Column('three_reps', sa.Float(), nullable=True),
    sa.Column('four_reps', sa.Float(), nullable=True),
    sa.Column('five_reps', sa.Float(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_press_personal_records_timestamp'), 'press_personal_records', ['timestamp'], unique=False)
    op.create_table('squat_personal_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('one_rep', sa.Float(), nullable=True),
    sa.Column('two_reps', sa.Float(), nullable=True),
    sa.Column('three_reps', sa.Float(), nullable=True),
    sa.Column('four_reps', sa.Float(), nullable=True),
    sa.Column('five_reps', sa.Float(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_squat_personal_records_timestamp'), 'squat_personal_records', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_squat_personal_records_timestamp'), table_name='squat_personal_records')
    op.drop_table('squat_personal_records')
    op.drop_index(op.f('ix_press_personal_records_timestamp'), table_name='press_personal_records')
    op.drop_table('press_personal_records')
    op.drop_index(op.f('ix_posts_title'), table_name='posts')
    op.drop_index(op.f('ix_posts_timestamp'), table_name='posts')
    op.drop_table('posts')
    op.drop_index(op.f('ix_maxes_timestamp'), table_name='maxes')
    op.drop_table('maxes')
    op.drop_table('general_settings')
    op.drop_index(op.f('ix_deadlift_personal_records_timestamp'), table_name='deadlift_personal_records')
    op.drop_table('deadlift_personal_records')
    op.drop_index(op.f('ix_bench_personal_records_timestamp'), table_name='bench_personal_records')
    op.drop_table('bench_personal_records')
    op.drop_table('accessory_lifts')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
