"""add other lift pr tables

Revision ID: aaf838bdb0d8
Revises: 083042a08455
Create Date: 2020-03-21 16:49:06.859412

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aaf838bdb0d8'
down_revision = '083042a08455'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bench_personal_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('one_rep', sa.Float(), nullable=True),
    sa.Column('two_reps', sa.Float(), nullable=True),
    sa.Column('three_reps', sa.Float(), nullable=True),
    sa.Column('four_reps', sa.Float(), nullable=True),
    sa.Column('five_reps', sa.Float(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bench_personal_records_timestamp'), 'bench_personal_records', ['timestamp'], unique=False)
    op.create_table('deadlift_personal_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('one_rep', sa.Float(), nullable=True),
    sa.Column('two_reps', sa.Float(), nullable=True),
    sa.Column('three_reps', sa.Float(), nullable=True),
    sa.Column('four_reps', sa.Float(), nullable=True),
    sa.Column('five_reps', sa.Float(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_deadlift_personal_records_timestamp'), 'deadlift_personal_records', ['timestamp'], unique=False)
    op.create_table('press_personal_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('one_rep', sa.Float(), nullable=True),
    sa.Column('two_reps', sa.Float(), nullable=True),
    sa.Column('three_reps', sa.Float(), nullable=True),
    sa.Column('four_reps', sa.Float(), nullable=True),
    sa.Column('five_reps', sa.Float(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_press_personal_records_timestamp'), 'press_personal_records', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_press_personal_records_timestamp'), table_name='press_personal_records')
    op.drop_table('press_personal_records')
    op.drop_index(op.f('ix_deadlift_personal_records_timestamp'), table_name='deadlift_personal_records')
    op.drop_table('deadlift_personal_records')
    op.drop_index(op.f('ix_bench_personal_records_timestamp'), table_name='bench_personal_records')
    op.drop_table('bench_personal_records')
    # ### end Alembic commands ###
